#################
### Load data ###
#################

rm(list=setdiff(ls(),c('params','measure','injection.site', 'seed', 'alt_seeds')))

basedir <- params$basedir
setwd(basedir)

alt_seed.dir <- paste0(basedir, params$opdir, 'alt_seeds/')
dir.create(alt_seed.dir,recursive = T)

savedir <- paste0(alt_seed.dir,paste0(seed,collapse='-'),'/')
dir.create(savedir,recursive = T)
paramdir <- paste0(params$opdir,'diffmodel/bidirectional_onelm/',paste0(params$injection.site,collapse='-'),'/')

source('code/misc/fitfxns.R')
source('code/misc/miscfxns.R')
source('code/misc/optimfxns.R')

tps=params$tps

load(paste0(paramdir,measure,'BidirectionalOptimOneLM_data.RData')) # load data to get time constants

# exclude regions with 0 pathology at each time point for purposes of computing fit
for(t. in 1:length(df)){colnames(df[[t.]]) <- c('y','pred.retro','pred.antero')} # rename regression predictors for consistency and interpretability. This should actually be done in optimfxns.R: lm.mask.ant.ret.all
lapply(1:length(tps), function(t) paste0(t,' MPI: ',sum(df[[t]]$y != -Inf & !is.na(df[[t]]$pred.retro)),'/',nrow(df[[t]]),' regions left'))

##########################################################
### add together anterograde and retrograde prediction ###
##########################################################

# m is linear regression model objects that combine anterograde and retrograde predictions at each time point
# generated by code/diffmodel/optim_bidirectionalspread_onelm.R
df.rnames <- lapply(df,rownames)
pred <- lapply(df.rnames, function(rn) m$fitted.values[rn])
path.t <- lapply(df.rnames, function(rn) m$model[rn,'y',drop=FALSE])


coefs <- m$coefficients
b.r <- coefs["x1"] # extract retrograde beta
b.a <- coefs["x2"] # extract anterograde beta
b.0 <- coefs["(Intercept)"] # extract B0 intercept
y <- m$model['y']
y <- setNames(y$y, rownames(y))
rm('df','m','m.fits') # eliminate unneeded variables
tps=params$tps

# load structural networks
W <- read.csv(paste0(params$opdir,'processed/W_full.csv'), header = FALSE) # load structural connectivity matrix
W <- as.matrix(W)
n.regions.ABA <- ncol(W)
regions <- read.csv(paste0(params$opdir,'processed/W_full_labeled.csv'), header = TRUE)
region.names <- regions$X # get region names corresponding to regions in connectivity dataset

L.out.retro <- get.Lout(W,rep(1,n.regions.ABA),ant.ret='retro') # compute out-degreee Laplacian for retrograde connectivity only
L.out.antero <- get.Lout(W,rep(1,n.regions.ABA),ant.ret='antero') # compute out-degreee Laplacian for anterograde connectivity only

Xo <- get.Xo(region.names,injection.site) # seed pathology in alternate seed site
scipy.sparse.linalg <- reticulate::import('scipy.sparse.linalg') # import scipy matrix exponential function because it's faster

# get predicted pathology
Xt.Grp.retro <- do.call('cbind',lapply(tps, function(t) log(quiet(predict.Lout(L.out.retro,Xo,c.Grp.retro,t,fxn=scipy.sparse.linalg$expm)),base=10))) # predict pathology using connectivity, time constant, and seed
Xt.Grp.antero <- do.call('cbind',lapply(tps, function(t) log(quiet(predict.Lout(L.out.antero,Xo,c.Grp.antero,t,fxn=scipy.sparse.linalg$expm)),base=10))) # predict pathology using connectivity, time constant, and seed

df.pred <- data.frame((b.0 + (b.r*Xt.Grp.retro) + (b.a*Xt.Grp.antero)))
colnames(df.pred) <- c('0.1 MPI', '0.2 MPI', '0.3 MPI', '0.5 MPI', '1 MPI', '3 MPI', '6 MPI', '9 MPI')

write.csv(df.pred,paste0(savedir,measure,'_log10predictedpath_bidirectional.csv'))

hemi.average.pred <- hemi.average(df.pred)
write.csv(hemi.average.pred,paste0(savedir,measure,'_log10predictedpath_bidirectional_hemiaverage.csv'))

# add a new column based on the prefix
df.pred.rl <- rownames_to_column(df.pred, var = "region")
df.pred.rl <- df.pred.rl %>%
  mutate(side = ifelse(substr(region, 1, 1) == "i", "right", "left")) %>%
  select(region, side, everything())
# remove the prefix from the names
df.pred.rl$region <- sub("^i|^c", "", df.pred.rl$region)
write.csv(df.pred.rl,paste0(savedir,measure,'_log10predictedpath_bidirectional_rl.csv'), row.names = FALSE) # save predictions in this format
