#################
### Load data ###
#################

rm(list=setdiff(ls(),c('params','measure','injection.site')))

basedir <- params$basedir
setwd(basedir)
savedir <- paste0(params$opdir,'diffmodel/bidirectional_onelm/',paste0(injection.site,collapse='-'),'/')
dir.create(savedir,recursive=T)

source('code/misc/fitfxns.R')
source('code/misc/miscfxns.R')
source('code/misc/plottingfxns.R')
load(paste0(params$opdir,'processed/',measure,'data.RData'))  # load path data and ROI names
load(paste0(savedir,measure,'BidirectionalOptimOneLM_data.RData'))
tps=params$tps
col <- 'orange'
# for cell body--no pathology to predict at 0.1 and 0.2 MPI, so exclude those time points
if (measure == "cell_body_path") {
  tps <- c(0.3, 0.5, 1, 3, 6, 9)
  df[[1]] <- NULL
  df[[1]] <- NULL
}

# exclude regions with 0 pathology at each time point for purposes of computing fit
for(t. in 1:length(df)){colnames(df[[t.]]) <- c('y','pred.retro','pred.antero')} # rename regression predictors for consistency and interpretability. This should actually be done in optimfxns.R: lm.mask.ant.ret.all
lapply(1:length(tps), function(t) paste0(t,' MPI: ',sum(df[[t]]$y != -Inf & !is.na(df[[t]]$pred.retro)),'/',nrow(df[[t]]),' regions left'))

##########################################################
### add together anterograde and retrograde prediction ###
##########################################################

# m is linear regression model objects that combine anterograde and retrograde predictions at each time point
# generated by code/diffmodel/optim_bidirectionalspread_onelm.R
df.rnames <- lapply(df,rownames)
vulnerability <- lapply(df.rnames, function(rn) residuals(m)[rn])
pred <- lapply(df.rnames, function(rn) m$fitted.values[rn])
path.t <- lapply(df.rnames, function(rn) m$model[rn,'y',drop=FALSE])

## below change pred to pred.test if using alternate seed prediction
p <- lapply(1:length(tps), function(t) 
  p.xy(x=pred[[t]],y=path.t[[t]],ylab='Log(pathology)',xlab='Log(predicted)',
       ttl=paste0(tps[t],' MPI'),col=col,alpha=0.7))
p <- plot_grid(plotlist=p,align='hv',nrow=1)
ggsave(p,filename = paste0(savedir,measure,'Fit_bidirectionaladditivemodel.pdf'),
       units = 'cm',height = 3.75,width = 3.75*length(tps),useDingbats=FALSE)

# plot fit and label each region
geom_label_repel(aes(label = Region),
                 point.padding = 0.5,
                 segment.color = 'grey50')
p <- list()
for(t. in 1:length(tps)){
  t.path.names <- substr(names(pred[[t.]]),1,nchar(names(pred[[t.]]))-2)
  df.tmp <- data.frame(x=pred[[t.]],y=path.t[[t.]],lab=t.path.names)
  df.tmp$z <- scale(df.tmp$x,center=T)
  df.tmp <- df.tmp[abs(df.tmp$z) >1.5,]
  p[[t.]] <- p.xy(x=pred[[t.]],y=path.t[[t.]],ylab='Log(pathology)',xlab='Log(predicted)',
   ttl=paste0(tps[t.],' MPI'),col=col,alpha=0.7) + geom_label_repel(data=df.tmp,aes(x=x,y=y,label=lab),
                     point.padding = 0.5,label.size=0.05,size=1,label.r=0.1,
                     segment.color = 'grey50')
}
  
p <- plot_grid(plotlist=p,align='hv',nrow=1)
ggsave(p,filename = paste0(savedir,measure,'Fit_bidirectionaladditivemodel_label_repel.pdf'),
       units = 'cm',height = 3.75,width = 3.75*length(tps),useDingbats=FALSE)

# plot fit and separately display hemispheres

p <- lapply(1:length(tps), function(t) 
  p.xyc(x=pred[[t]],y=path.t[[t]],ca=substr(rownames(path.t[[t]]),1,1),ylab='Log(pathology)',xlab='Log(predicted)',
        ttl=paste0(tps[t],' MPI'),col=col,alpha=0.7) + 
    theme(legend.position = c(0.1,1),legend.background=element_blank(),legend.key.size = unit(0.1, "cm"),legend.title = element_blank()))
p <- plot_grid(plotlist=p,align='hv',nrow=1)
ggsave(p,filename = paste0(savedir,measure,'FitHemiColor_bidirectionaladditivemodel.pdf'),
       units = 'cm',height = 3.75,width = 3.75*length(tps),useDingbats=FALSE)

# initialize empty data frame with all regions and time points
df.vuln <- df.pred <- data.frame(matrix(ncol=length(tps),nrow=length(path.names), dimnames=list(path.names, paste(tps,'MPI'))),check.names = FALSE)
for(t in 1:length(tps)){
  regions.mpi <- names(vulnerability[[t]]) # get the regions that had non-zero pathology at each tp (so log can be computed)
  regions.mpi.path.names <- substr(regions.mpi,1,nchar(regions.mpi)-2) # get names of regions without "_1" ("_$MPI") appended
  df.vuln[regions.mpi.path.names,paste(tps[t],'MPI')] <- vulnerability[[t]][regions.mpi]
  df.pred[regions.mpi.path.names,paste(tps[t],'MPI')] <- pred[[t]][regions.mpi]
}

# compute intrinsic vulnerability as an average over time and hemispheres
hemi.average.vuln <- hemi.average(df.vuln)
write.csv(hemi.average.vuln,paste0(savedir,measure,'_vulnerability_bidirectional_hemiaverage.csv'))

# look at only 1, 3, 6, 9 MPI tps
df.vuln.excl <- df.vuln %>%
  select('1 MPI', '3 MPI', '6 MPI', '9 MPI')
hemi.average.vuln.1.3.6.9.MPI <- hemi.average(df.vuln.excl)
write.csv(hemi.average.vuln.1.3.6.9.MPI,paste0(savedir,measure,'_vulnerability_bidirectional_hemiaverage_1.3.6.9.MPI.csv'))

write.csv(df.vuln,paste0(savedir,measure,'_vulnerability_bidirectional.csv')) # save vulnerability for each time point

write.csv(df.pred,paste0(savedir,measure,'_log10predictedpath_bidirectional.csv')) # save log10 predicted path
df.pred.rl <- rownames_to_column(df.pred, var = "region")
df.pred.rl <- df.pred.rl %>%
  mutate(side = ifelse(substr(region, 1, 1) == "i", "right", "left")) %>%
  select(region, side, everything())
# Remove the prefix from the names
df.pred.rl$region <- sub("^i|^c", "", df.pred.rl$region)
write.csv(df.pred.rl,paste0(savedir,measure,'_log10predictedpath_bidirectional_rl.csv')) # save log10 predicted path

# Add a new column based on the prefix
df.vuln.rl <- rownames_to_column(df.vuln, var = "region")
df.vuln.rl <- df.vuln.rl %>%
  mutate(side = ifelse(substr(region, 1, 1) == "i", "right", "left")) %>%
  select(region, side, everything())
# Remove the prefix from the names
df.vuln.rl$region <- sub("^i|^c", "", df.vuln.rl$region)
write.csv(df.vuln.rl,paste0(savedir,measure,'_vulnerability_bidirectional_rl.csv'), row.names = FALSE) # save vulnerability in this format

